/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/auth/auth.vue')['default']
    AuthAll: typeof import('./components/auth/authAll.vue')['default']
    Auths: typeof import('./components/auth/auths.vue')['default']
    Cropper: typeof import('./components/cropper/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    IconSelector: typeof import('./components/iconSelector/index.vue')['default']
    List: typeof import('./components/iconSelector/list.vue')['default']
    NoticeBar: typeof import('./components/noticeBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svgIcon/index.vue')['default']
    Table: typeof import('./components/table/index.vue')['default']
  }
}
